### PR TITLE
Added the ability to disable opening menu on keyboard

### PR DESCRIPTION
**Pull request by AylaMeo**
works the same as disabling input for controller

### CODE REVIEW

**Comment by TomGrobbe** [comment]
@Alsekwolf You should be able in this case to just set the control toggle key to something like -1 or -2 and it should also work

**Comment by Alsekwolf** [comment]
unless I'm missing something, "MenuController.MenuToggleKey" only accepts "CitizenFX.core.control"

**Comment by TomGrobbe** [comment]
@Alsekwolf ((CitizenFX.Core.Control)(-1)) that should work

**Comment by Alsekwolf** [comment]
ahh, might be useful to throw that in the docs.

**Pull request closed without merging**
